# Site name
site_name: DE5-M6 ~ Data Operations
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - Day 1 - Monitoring & Performance:
    - Foundation & Purpose: day1/foundation-purpose.md
    - Lab 1 - Ingest Data: labs/04-ingest-pipeline.md
    - Lab 2 - Monitor Activity: labs/18-monitor-hub.md
    - Lab 3 - Monitor Data Warehouse: labs/06c-monitor-data-warehouse.md
    - Cloud Monitoring Comparison: day1/cloud-monitoring-comparison.md
    - Monitoring Strategy Creation: day1/monitoring-strategy.md

 - Day 2 - Incident Response:
    - Welcome & Context Setting: day2/welcome-context.md
    - Breaking Things 101: day2/breaking-things.md
    - Lab 1 - Setup Alerts: labs/11-data-activator.md
    - Activity - Outage Case Studies: day2/outage-case-studies.md
    - Activity - Incident Response Practice: day2/incident-response-practice.md
    - Activity - Workplace Procedures: day2/workplace-procedures.md
    - Activity - Response Checklist Creation: day2/response-checklist.md

  - Day 3 - Quality & Governance:
    - Lab 1 - Medallion Architecture: labs/03b-medallion-lakehouse.md
    - Lab 2 - Security Data Access: labs/19-secure-data-access.md
    - Activity - Governance Scenarios: day3/governance-scenarios.md

  - Day 4 - Improvement & Value:
    - Lab 1 - Operational Deployment: labs/21-implement-cicd.md
    - Activity - Technology Assessment: day4/technology-assessment.md
    - Activity - Value Presentation: day4/value-presentation.md

  - Resources: resources.md

# Theme
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/database
    static_templates:
      - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
